# Generated by Django 4.2.2 on 2024-10-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subdomain", models.CharField(max_length=2000)),
                ("domain", models.CharField(db_index=True, max_length=64)),
                ("suffix", models.CharField(db_index=True, max_length=64)),
                ("last_seen", models.DateField(db_index=True)),
            ],
        ),
    ]
