name: QA and image building

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    environment: Default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # This helps with adding version information to the build in the admin on production. CI usually works shallow.
      # https://stackoverflow.com/questions/4916492/git-describe-fails-with-fatal-no-names-found-cannot-describe-anything
      # this will fetch the whole repository, which is more expensive.
      - run: git fetch --prune --unshallow --tags

      - name: build images
        run: |
          VERSION=$(git describe --tags --abbrev=0)-$(git log -1 --pretty=format:%h)
          make build build_args=--build-arg=VERSION=${VERSION:-0.0.0-dev0}

      - name: check
        run: make check

      - name: lint
        run: make lint

      - name: test
        run: make up test rm

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to docker hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          make push_images
